#!/bin/sh

if [ -z "$1" ]; then
  echo "$0 [repo host]"
  exit 1
else
  repohost=$1
fi

private_repohost=stick@neurosis.miscellaneous.net

# setup homedir
printf "Home is $HOME... Proceed? "
read ANS

case $ANS in
  y|Y|yes|Yes|YEs|YES|yEs|yES|yeS)
    true
    ;;
  *)
    echo "Quiting."
    exit 0
esac

./dotfiles/bin/homesync.sh setup $(pwd)

ln -sf ~/.bashrc ~/.bash_profile

# clone ssh config repo
git clone ${private_repohost}:ssh-config.git .ssh

# clone vi configs
set -x
git clone ssh://${repohost}/vimfiles.git .vim
set +x
ln -s ~/.vim/vimrc ~/.vimrc
ln -s ~/.vim/gvimrc ~/.gvimrc

# gnupg
git clone ${private_repohost}:gnupg-config.git .gnupg

# mac
case $MACHTYPE in
  *-apple-darwin*)
    if [ -e "$HOME/.macports" ]; then
      echo "looks like no macports, you probably want that for unix utils"
    else
      echo "You really probably need to install the following from macports to avoid odd behavior"
      echo "    bash-completion"
      echo "    coreutils (color ls mainly)"
      echo "    ctags"
      echo "    vim (macos version lags behind)"
    fi
    ;;
esac
