#!/bin/sh

noop="--noop"
for ob in $*; do
  case "$ob" in
    --force)  noop="" ;;
    --*) options="${options} ${ob}" ;;
    *) classes="${classes} ${ob}" ;;
  esac
done
for class in $classes; do
  echo "include $class"
done | puppet apply $noop --verbose $options
